//========= Copyright (C) 2026 3zymek, MIT License ============//
//
// Auto-generated by Lumen Header Compiler (LHC).
// Repository: https://github.com/3zymek/Lumen-Header-Compiler
// Source: scene_dependency_manager.generated.hpp
//
// DO NOT EDIT - changes will be overwritten on next build.
//
//=============================================================================//
#pragma once
#include "modules/scene/format/scene_parser.hpp"
#include "C:/Users/szymek/Desktop/LumEngine/LumEngine/engine/include/modules/entity/components/transform.hpp"

namespace lum::fmt::detail {

	inline void RegisterComponents( std::unordered_map<uint64, ParseFn>& map ) {
		map[ HashStr("transform") ] = ParseCTransform;
	}

}
