#pragma once

#include <iostream>
#include <string>
#include <chrono>
#include <thread>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <vector>
#include <unordered_map>
#include <exception>
#include <type_traits>
#include <cstddef>
#include <cstring>
#include <memory>
#include <array>
#include <optional>
#include <span>
#include <algorithm>
#include <utility>
#include <string_view>
#include <fstream>
#include <sstream>
#include <cmath>

#include "math/backend/glm.hpp"
#include "math/backend/gtc/matrix_transform.hpp"
#include "math/backend/gtc/type_ptr.hpp"