//========= Copyright (C) 2026 3zymek, MIT License ============//
//
// Auto-generated by Lumen Header Compiler (LHC).
// Repository: https://github.com/3zymek/Lumen-Header-Compiler
// Source: transform.hpp
//
// DO NOT EDIT - changes will be overwritten on next build.
//
//=============================================================================//
#pragma once
#include "modules/scene/format/scene_parser.hpp"

namespace lum::fmt::detail {

	void ParseCTransform( std::vector<FToken>& tokens, int32& i, FParseContext& ctx ){

		detail::ExpectOpeningBracket( tokens, i );

		CTransform component; 

		while( in_block( tokens, i ) ) {
			if( tokens[i].mType == TokenType::Parameter ) {
				if( detail::IsString( tokens, i, "mPosition" ) )
					component.mPosition = detail::ReadVec3Parameter( tokens, i );
				else if( detail::IsString( tokens, i, "mScale" ) )
					component.mScale = detail::ReadVec3Parameter( tokens, i );
				else if( detail::IsString( tokens, i, "mRotation" ) )
					component.mRotation = detail::ReadVec3Parameter( tokens, i );
			}
			i++;
		}

		ctx.mScene.mEntityMgr.AddComponent( ctx.mEntity, component );

	}
} // namespace lum::fmt::detail
